# Generated by Django 3.1.7 on 2021-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountnumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
