# Generated by Django 3.1.7 on 2021-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20210513_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounttype',
            field=models.CharField(default='savings account', max_length=20),
        ),
    ]
