# Generated by Django 3.1.7 on 2021-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_user_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(default='aaaaaa', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(default='aaaaa', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc_no',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
