# Generated by Django 3.1.7 on 2021-06-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_auto_20210518_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=20)),
                ('semester', models.IntegerField(max_length=10)),
                ('mailid', models.EmailField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
