# Generated by Django 3.1.7 on 2021-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=30)),
                ('desired_loan_amount', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('loan_required_for', models.CharField(choices=[('HomeLoan', 'HomeLoan'), ('EducationLoan', 'EducationLoan'), ('GoldLoan', 'GoldLoan'), ('CarLoan', 'CarLoan')], max_length=50)),
                ('loan_duration', models.IntegerField()),
                ('phonenumber', models.BigIntegerField(max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved'), ('pending', 'pending')], max_length=50)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('intrest', models.IntegerField(blank=True, null=True)),
                ('max_loan', models.IntegerField()),
            ],
        ),
    ]
