# Generated by Django 3.2.3 on 2021-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(default=None, max_length=15)),
                ('balance', models.IntegerField(default=None)),
                ('username', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_number', models.CharField(max_length=15)),
                ('dest_account_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Recieved_from', 'Recieved_from'), ('Transfered_to', 'Transfered_to')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
