# Generated by Django 3.1.7 on 2021-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ifsc_no',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
